packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@prisma/engines'
  - argon2
  - esbuild
  - prisma
  - unrs-resolver
patchedDependencies:
  react-native-css-interop@0.2.6: patches/react-native-css-interop@0.2.6.patch
